In [1]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [2]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

l2_dist(a.T,b.T)

NameError: name 'a' is not defined

In [4]:
import numpy as np
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)


In [5]:
a1.shape == a2.shape

False

In [6]:
a3.shape == a4.shape

False

In [7]:
a4.ndim() == 1

TypeError: 'int' object is not callable

In [8]:
a5.shape == a1.shape

True

In [10]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)



[[0 0 1]
 [1 1 1]]


In [12]:
import re
s = 'ACBCAC'

re.findall('^AC(.+)',s)

['BCAC']

In [13]:
re.findall('AC',s)

['AC', 'AC']

In [14]:
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

In [15]:
print(L)

5


In [18]:
test = """Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad"""

In [17]:
re.findall('[(]\d{3}[)]\s\d{3}[-]\d{4}',test)

['(734) 647-6333',
 '(734) 647-8044',
 '(734) 763-2285',
 '(734) 647-3576',
 '(734) 763-1251',
 '(734) 764-9376']

In [19]:
test1 = """I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything"""

In [26]:
for item in re.finditer('(?<=[https]:\/\/)([A-Za-z0-9.]*)',test1):
    print(item)

<re.Match object; span=(19, 29), match='google.com'>
<re.Match object; span=(55, 68), match='www.baidu.com'>


In [27]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''

In [31]:
len(re.findall('\(.\)',text))

4

In [32]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]
