# Numpy

In [1]:
import numpy as np

# Creating Arrays

In [2]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
m.shape

(2, 3)

In [5]:
n = np.arrange(0,30,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
n = np.arange(0,30,2)

In [7]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [9]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [10]:
o.resize(3,3)

In [11]:
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [12]:
one = np.ones((3,2))

In [13]:
one


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.diag(4)

ValueError: Input must be 1- or 2-d.

In [16]:
np.diag(y)

NameError: name 'y' is not defined

In [17]:
np.diag(3)

ValueError: Input must be 1- or 2-d.

In [18]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])